# Generated by Django 4.2.15 on 2024-09-05 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('protocolo', models.CharField(blank=True, choices=[('mqtt', 'MQTT'), ('http', 'HTTP')], max_length=200, null=True)),
                ('identificador', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iot.dispositivo')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iot.variable')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='variables',
            field=models.ManyToManyField(to='iot.variable'),
        ),
    ]
