# Generated by Django 4.2.15 on 2024-09-05 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('iot', '0002_dispositivo_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.municipio'),
        ),
    ]
