# Generated by Django 4.2.15 on 2024-09-06 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iot', '0003_dispositivo_usuario_alter_dispositivo_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='usuario',
            field=models.ManyToManyField(blank=True, null=True, related_name='dispositivos', to=settings.AUTH_USER_MODEL),
        ),
    ]
