# Generated by Django 4.2.15 on 2024-09-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_alter_dispositivo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrovariable',
            name='dispositivo',
        ),
        migrations.RemoveField(
            model_name='registrovariable',
            name='variable',
        ),
        migrations.DeleteModel(
            name='Dispositivo',
        ),
        migrations.DeleteModel(
            name='RegistroVariable',
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
    ]
