# Generated by Django 4.2.15 on 2024-09-06 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('protocolo', models.CharField(blank=True, choices=[('mqtt', 'MQTT'), ('http', 'HTTP')], max_length=200, null=True)),
                ('identificador', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('municipio', models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='provincia',
        ),
        migrations.CreateModel(
            name='RegistroVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.dispositivo')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.variable')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='variables',
            field=models.ManyToManyField(to='accounts.variable'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dispositivos',
            field=models.ManyToManyField(related_name='usuarios', to='accounts.dispositivo'),
        ),
    ]
