# Generated by Django 4.2.15 on 2024-09-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dispositivo_variable_remove_usuario_provincia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovariable',
            name='unidad',
            field=models.CharField(default='C', max_length=10),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='identificador',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='accounts.municipio'),
        ),
    ]
