# Generated by Django 4.2.15 on 2024-09-09 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_variable_limite_inferior_variable_limite_superior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dispositivos', to='accounts.municipio'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipios', to='accounts.provincia'),
        ),
    ]
