# Generated by Django 4.2.15 on 2024-11-01 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_dispositivo_municipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='carnet_identidad',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dispositivos',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='accounts.dispositivo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='phone',
            field=models.CharField(blank=True, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 8 dígitos.', regex='^\\d{8}$')]),
        ),
    ]
