# Generated by Django 4.2.15 on 2024-11-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_provincia_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivo',
            old_name='identificador',
            new_name='nombre_identificador',
        ),
    ]
